import Image from 'next/image'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Header from '@/components/Organisms/Header'
import Footer from '@/components/Organisms/Footer'
import MobileMenu from '@/components/Molecules/MobileMenu'
import axiosCms from '@/libs/axioscms'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const getData = async () => {
  const data = await axiosCms('/api/globals/Header')
  return data.data
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const globalData = await getData()
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen relative`}>
        <Header navLinks={globalData.navLinks} />
        <div className="px-4 2xl:px-0 pt-[148px] lg:pt-[278px] pb-[57px] lg:pb-[108px] min-h-[60vh]">
          {children}
        </div>
        <Footer />
        <MobileMenu activeLink={'/'} />
      </body>
    </html>
  )
}
