import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import payload from '@/libs/payload'
import HeaderSection from '@/components/Organisms/Header'
import Footer from '@/components/Organisms/Footer'
import MobileMenu from '@/components/Molecules/MobileMenu'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const getLoaderData = async () => {
  const HeaderData = await payload.findGlobal({ slug: 'Header', showHiddenFields: false })
  return { HeaderData }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { HeaderData } = await getLoaderData()

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen relative`}>
        <HeaderSection {...HeaderData} />
        <div className="px-4 2xl:px-0 pt-[148px] lg:pt-[278px] pb-[57px] lg:pb-[108px] min-h-[60vh]">
          {children}
        </div>
        <Footer />
        <MobileMenu activeLink={'/'} />
      </body>
    </html>
  )
}
