import Image from 'next/image';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Header from '@/components/Organisms/Header';
import Footer from '@/components/Organisms/Footer';
import MobileMenu from '@/components/Molecules/MobileMenu';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="lg:max-w-[1024px] mx-auto w-full">{children}</div>
        <Footer />
        <MobileMenu activeLink={'/'} />
      </body>
    </html>
  );
}
